### ISSUE TITLE
The grid function were not working in Sketch 3.4.4

### ISSUE THREAD

**Issue by tankxu** [alssndro/sandros-sketch-plugins#14] opened 2016-01-11 08:01 UTC

**Comment by alssndro** [comment] 2016-01-11 19:45
I have fixed one of the plugins that was still using the old Sketch plugin format in this commit: d5255bcbb4991cd997e64628c6ba6516b058b5c7.

However this may not be the same issue you are experiencing. 

Please give more information about the exact plugin that is not working, and the steps you are taking, so that I can reproduce the error.

**Comment by alssndro** [comment] 2016-01-28 19:12
Closing since it can't be reproduced, will reopen if this changes.

**Closed by alssndro** 2016-01-28 19:12 UTC
